global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'flask-api-monitor'

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['localhost:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
